apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: notejam
        env: {{ .Values.labels.env }}
        cluster: {{ .Values.labels.cluster }}
    spec:
      containers:
        - name: notejam
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.labels.env }}
            {{- if .Values.mail.enabled }}
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: host
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: port
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: smtp-auth
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: smtp-starttls-enabled
            {{- end }}
            {{- if .Values.externalDatabase.enabled }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://$(DATABASE_HOST)/{{ .Values.labels.env }}
            {{- end }}
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5