{{- if .Values.mail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  labels: notejam
type: Opaque
data:
  host: {{ .Values.mail.host }}
  username: {{ .Values.mail.username }}
  password: {{ .Values.mail.password }}
  port: {{ .Values.mail.port }}
  smtp-auth: {{ .Values.mail.smtp-auth }}
  smtp-starttls-enabled: {{ .Values.mail.smtp-starttls-enabled }}
{{- end }}