{{- if .Values.mail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  labels: 
    app: notejam
    env: {{ .Values.labels.env }}
    cluster: {{ .Values.labels.cluster }}
type: Opaque
data:
  host: {{ .Values.mail.host | b64enc | quote}}
  username: {{ .Values.mail.username | b64enc | quote}}
  password: {{ .Values.mail.password | b64enc | quote}}
  port: {{ .Values.mail.port | b64enc | quote}}
  smtp-auth: {{ .Values.mail.smtpAuth | b64enc | quote}}
  smtp-starttls-enabled: {{ .Values.mail.smtpStarttlsEnabled | b64enc | quote}}
{{- end }}