image:
  repository: fbdo/notejam
  tag: latest
  pullPolicy: Always

labels:
  env: "dev"

externalDatabase:
  enabled: false

mail:
  enabled: false

resources:
  limits:
    cpu: 4
    memory: 512Mi
  requests:
    memory: 256Mi
    cpu: 1
