image:
  repository: fbdo/notejam
  tag: latest
  pullPolicy: Always

labels:
  env: "dev"

externalDatabase:
  enabled: true

mail:
  enabled: true

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    memory: 2Gi
    cpu: 2

hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuAverageUtilization: 65
  memoryTargetAverageValue: 1Gi
