image:
  registry: docker.io
  repository: fbdo/notejam
  tag: 0.1.0
  pullPolicy: IfNotPresent

labels:
  env: "prod"
  cluster: "notejam"

service:
  port: 80
  targetPort: 8080
  type: LoadBalancer

resources:
  limits:
    cpu: 6
    memory: 6Gi
  requests:
    memory: 4Gi
    cpu: 4

hpa:
  minReplicas: 3
  maxReplicas: 6
  cpuAverageUtilization: 65
  memoryTargetAverageValue: 4Gi

externalDatabase:
  enabled: true
  host: localhost
  user: notejam
  password: ""
  database: notejam
  port: 3306

mail:
  enabled: false
  host: smtp.gmail.com
  username: notejam@notejam.com
  password: ""
  port: "587"
  smtpAuth: "true"
  smtpStarttlsEnabled: "true"
