name: Build/Deploy notejam app

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Java compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: mvn -f spring/pom.xml compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Test and package project
        run: mvn -f spring/pom.xml package
  publish_docker:
    runs-on: ubuntu-latest
    needs: build
    name: Build Docker container and publish to registry
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker container
        run: mvn -f spring/pom.xml com.google.cloud.tools:jib-maven-plugin:build -Dimage=fbdo/notejam
