name: Continuous Integration notejam app

on:
  push:
    branches:
      - develop
      - feature/*
      - release/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and package
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Test and package project
        run: mvn -f spring/pom.xml package
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: spring/target/app.jar
  publish_docker:
    runs-on: ubuntu-latest
    needs: build
    name: Build Docker container and publish to registry
    steps:
      - uses: actions/checkout@v1
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Publish to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          mkdir -p spring/target
          mv artifact/app.jar spring/target
          docker build -t fbdo/notejam:latest  spring
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push fbdo/notejam:latest
  deploy_helm:
    runs-on: ubuntu-latest
    needs: publish_docker
    name: Deploy helm chart
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Setup GCP credentials"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true
      - name: Deploy Helm chart
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials notejam --zone=europe-west3-a --project ${{ secrets.GCP_PROJECT_ID }}
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm upgrade -f spring/charts/notejam/values-dev.yaml notejam spring/charts/notejam --install --namespace=dev
