name: Continuous Deployment notejam app Dev

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy_helm:
    runs-on: ubuntu-latest
    name: Deploy helm chart
    if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Setup GCP credentials"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true
      - name: Deploy Helm chart to Dev
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials notejam --zone=europe-west3-a --project ${{ secrets.GCP_PROJECT_ID }}
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm upgrade -f spring/charts/notejam/values-dev.yaml notejam spring/charts/notejam --install --namespace=dev --set image.tag=latest
