name: Continuous Deployment QA

on:
  push:
    branches:
      - release/*
      - hotfix/*
      - feature/*

jobs:
  release:
    name: Deploy on preview environment
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/heads/release/}

          echo "::set-env name=RELEASE_VERSION::$VERSION"
      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.ref, 'refs/heads/hotfix/')
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/heads/hotfix/}

          echo "::set-env name=RELEASE_VERSION::$VERSION"
      - name: Extract version from branch name (for feature branches)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/heads/feature/}

          echo "::set-env name=RELEASE_VERSION::$VERSION"
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Setup GCP credentials"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true
      - name: Deploy Helm chart to QA
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials notejam --zone=europe-west3-a --project ${{ secrets.GCP_PROJECT_ID }}
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm upgrade -f spring/charts/notejam/values-qa.yaml notejam spring/charts/notejam --install --namespace=${{ env.RELEASE_VERSION }} --set image.tag=${{ env.RELEASE_VERSION }}
