name: Delete namespaces preview environments

on:
  delete:
    branches:
      - release/*
      - hotfix/*
      - feature/*

jobs:
  tag:
    name: Extract branch name
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/heads/release/}

          echo "::set-env name=RELEASE_VERSION::$VERSION"
      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.ref, 'refs/heads/hotfix/')
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/heads/hotfix/}

          echo "::set-env name=RELEASE_VERSION::$VERSION"
      - name: Extract version from branch name (for feature branches)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/heads/feature/}

          echo "::set-env name=RELEASE_VERSION::$VERSION"
      - name: "Setup GCP credentials"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true
      - name: Delete namespace for preview environment
        run: |
          NAMESPACE="${RELEASE_VERSION//[.]/-}"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials notejam --zone=europe-west3 --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl delete namespace $NAMESPACE
